/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAskRouteImport } from './routes/app/ask'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppExpertRouteImport } from './routes/app/expert'
import { Route as AppFinanceRouteImport } from './routes/app/finance'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppFinanceBankRouteImport } from './routes/app/finance.bank'
import { Route as AppMarketSellRouteImport } from './routes/app/market.sell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertRoute = AppExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceBankRoute = AppFinanceBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppMarketSellRoute = AppMarketSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppMarketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ask': typeof AppAskRoute
  '/app/book': typeof AppBookRoute
  '/app/expert': typeof AppExpertRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/market': typeof AppMarketRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/finance/bank': typeof AppFinanceBankRoute
  '/app/market/sell': typeof AppMarketSellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ask': typeof AppAskRoute
  '/app/book': typeof AppBookRoute
  '/app/expert': typeof AppExpertRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/market': typeof AppMarketRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/finance/bank': typeof AppFinanceBankRoute
  '/app/market/sell': typeof AppMarketSellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ask': typeof AppAskRoute
  '/app/book': typeof AppBookRoute
  '/app/expert': typeof AppExpertRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/market': typeof AppMarketRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/finance/bank': typeof AppFinanceBankRoute
  '/app/market/sell': typeof AppMarketSellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ask'
    | '/app/book'
    | '/app/expert'
    | '/app/finance'
    | '/app/knowledge'
    | '/app/market'
    | '/app/'
    | '/app/finance/bank'
    | '/app/market/sell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ask'
    | '/app/book'
    | '/app/expert'
    | '/app/finance'
    | '/app/knowledge'
    | '/app/market'
    | '/app'
    | '/app/finance/bank'
    | '/app/market/sell'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ask'
    | '/app/book'
    | '/app/expert'
    | '/app/finance'
    | '/app/knowledge'
    | '/app/market'
    | '/app/'
    | '/app/finance/bank'
    | '/app/market/sell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expert': {
      id: '/app/expert'
      path: '/expert'
      fullPath: '/app/expert'
      preLoaderRoute: typeof AppExpertRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/bank': {
      id: '/app/finance/bank'
      path: '/bank'
      fullPath: '/app/finance/bank'
      preLoaderRoute: typeof AppFinanceBankRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/market/sell': {
      id: '/app/market/sell'
      path: '/sell'
      fullPath: '/app/market/sell'
      preLoaderRoute: typeof AppMarketSellRouteImport
      parentRoute: typeof AppMarketRoute
    }
  }
}

interface AppFinanceRouteChildren {
  AppFinanceBankRoute: typeof AppFinanceBankRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceBankRoute: AppFinanceBankRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppMarketRouteChildren {
  AppMarketSellRoute: typeof AppMarketSellRoute
}

const AppMarketRouteChildren: AppMarketRouteChildren = {
  AppMarketSellRoute: AppMarketSellRoute,
}

const AppMarketRouteWithChildren = AppMarketRoute._addFileChildren(
  AppMarketRouteChildren,
)

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRoute
  AppBookRoute: typeof AppBookRoute
  AppExpertRoute: typeof AppExpertRoute
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMarketRoute: typeof AppMarketRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRoute,
  AppBookRoute: AppBookRoute,
  AppExpertRoute: AppExpertRoute,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMarketRoute: AppMarketRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
